services:
  database:
    image: pgvector/pgvector:pg17
    container_name: postgres-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - rag
  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    networks:
      - rag

  api:
    build: ./backend
    tty: true
    ports:
      - "5000:5000"
    networks:
      - rag
    env_file:
      - ./backend/.env
    volumes:
      - image-storage:/app/images

  celery-worker:
    build: ./backend
    command: celery -A celery_app worker --loglevel=WARNING --concurrency=5
    container_name: celery-worker
    networks:
      - rag
    volumes:
      - image-storage:/app/images
    env_file:
      - ./backend/.env

  # rag-gpu-service:
  #   build: ./gpu-service
  #   container_name: rag-gpu-service
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - rag

  # rag-chat-service:
  #   build: ./chat-service
  #   container_name: rag-chat-service
  #   ports:
  #     - "8001:8001"
  #   networks:
  #     - rag


  redis:
    container_name: redis-db
    image: redis:8-alpine
    networks:
      - rag
    volumes:
      - redis-data:/data

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8082:8081"
    networks:
      - rag

volumes:
  postgres-data:
  redis-data:
  image-storage:

networks:
  rag:
